source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.4'
use_frameworks!

target :'Mobile Shop'

pod 'SWXMLHash'
pod 'Alamofire'
pod 'AlamofireImage'
pod 'SwiftValidator'

pod ' ,PagedHorizontalView'
pod 'KYDrawerController'
pod 'DTIToastCenter'
pod 'SnappingStepper'
pod 'IQKeyboardManagerSwift'

pod 'OneSignal'
